### ISSUE TITLE
Include a more relevant image when sharing on social network sites

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/blog#19]
## What happened?

* What were you attempting to do?
I was trying to post one of the blog entries on LinkedIn.

* What did you expect to happen?
I expected the post to include a picture that was relevant to the post.

* What was the actual behavior? Please provide log output, if possible.
The image that LinkedIn chose to highlight was the author's portrait, which while important to see, was probably not the most relevant thing for folks to notice when they viewed my social media post.

<img width="622" alt="Screen Shot 2021-02-26 at 3 07 56 PM" src="https://user-images.githubusercontent.com/155736/109364830-8508fc80-7844-11eb-8a35-94599ac64a3f.png">

## Possible Fix
I believe the issue is that we don't have metadata at the top of the page that helps LinkedIn pick a good image. They outline in their [docs](https://www.linkedin.com/help/linkedin/answer/46687/making-your-website-shareable-on-linkedin?lang=en) that they are looking for an `og:image` `meta` tag. We [have tags](https://github.com/paketo-buildpacks/blog/blob/0e46a92ef754df1420131690727095ec200e604c/layouts/partials/head.html#L8-L10) for `og:site_name`, `og:title`, and `og:url`, but not `og:image`.

We should probably add this field and allow authors to set it in the post metadata. We should probably also include a good default image like the Paketo logo.

**Comment by sophiewigmore** [comment]
Fixed in https://github.com/paketo-buildpacks/blog/pull/23
