### ISSUE TITLE
Web Servers blog

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/blog#31]
With the introduction of zero config for httpd and nginx we should write a blog highlighting this new workflow.

**Comment by fg-j** [comment]
Blocked until nginx and httpd buildpacks are released with zero-config build capabilities.

**Comment by ForestEckhardt** [comment]
Both buildpacks have released this feature and various samples and documentation.

**Comment by ForestEckhardt** [comment]
Make this post about Web Servers as a whole
