### ISSUE TITLE
Add blog header

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/blog#9]
Could we add in the paketo.io header to the top of this page so it doesn't feel like a completely separate page, and provide some way to navigate back to the paketo website?
![image](https://user-images.githubusercontent.com/37810054/107087368-565db000-67c9-11eb-98c5-8ad67ae3a6e3.png)

**Comment by ForestEckhardt** [comment]
@kvedurmu I don't want the entire header. I think that would clutter the blog page. I do think that a link back to the main page might be nice but I don't think that it is super necessary because we force opening into a new tab.

**Comment by fg-j** [comment]
I agree on clutter. However at minimum a link from blog -> main Paketo site is crucial so someone who finds a blog post of ours on, say, Hackernews 😉  is able to find their way back to the project.

**Comment by ForestEckhardt** [comment]
I didn't even think about an external source. That is a great point!

**Comment by kvedurmu** [comment]
That all makes sense. I really just want some link back to the main website for the reasons @fg-j mentioned.
